" Vim configuration

set nocompatible    " Don't use old Vi settings
set autowrite

set noswapfile      " Disable swap file

syntax on           " Syntax highlighting

" Line numbers
set number
"set relativenumber

" Display
set nowrap          " Don't wrap lines
set scrolloff=8     " Keep cursor centered vertically

" Highlight trailing whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

" Indentation
set tabstop=4       " Show existing tab characters as 4 spaces
set shiftwidth=4    " When indenting use 4 spaces
set expandtab

" Enable the mouse and make sure if works for Alacritty too!
set mouse=a
if $TERM == 'alacritty'
    set ttymouse=sgr
endif

" Mappings

" Save on Ctrl+S
noremap <silent> <C-S> :update<CR>
vnoremap <silent> <C-S> <C-C>:update<CR>
inoremap <silent> <C-S> <C-O>:update<CR><ESC>

" Disable arrow keys
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
